feat(wiki): markdown editor
frappe/wiki pull request #265
Opened 2024-09-07 15:29 UTC by AyshaHakeem

- Add a patch to convert 'content' field's value in existing Wiki Page records from Rich Text (HTML) to Markdown
- Update the 'content' field's type in the Wiki Page Doctype to 'Markdown Editor’
- Convert existing editor to markdown in the frontend

2024-09-10 04:30 UTC, shariquerik requested changes

2024-09-10 04:30 UTC, shariquerik commented on wiki/public/js/editor.js
> +let show_preview = false;
Since all variables are in camelCase stick with camelCase

2024-09-10 04:30 UTC, shariquerik commented on wiki/public/js/render_wiki.js
> +  // $(".wiki-edit-control-btn").toggleClass("hide");
remove it if not required

2024-09-10 04:30 UTC, shariquerik commented on wiki/public/scss/edit_wiki.scss
Remove unused styles if there are any

2024-09-10 04:32 UTC, shariquerik commented
@AyshaHakeem Can you also fix the failing cypress test

2024-09-10 04:34 UTC, shariquerik commented
Suggestion: Always try to push in multiple and small commits instead of pushing everything in one commit. It will be easier for reviewer to read your PR.

2024-09-10 04:38 UTC, shariquerik commented
I was testing and tried to create CRM's Introduction page which works perfectly. But I have added a video tag is not visible in edit mode after saving. It is visible in desk but not in portal

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/cbd92a1e-8fed-41d5-9e18-ad7325bcc15b">


Desk:
<img width="921" alt="image" src="https://github.com/user-attachments/assets/4fe8ac24-652c-45a6-8d43-8b62994d2b58">

Portal:
<img width="1140" alt="image" src="https://github.com/user-attachments/assets/748827f2-7be8-468f-89c1-713ad45907eb">

2024-09-10 04:56 UTC, shariquerik requested changes

2024-09-10 04:56 UTC, shariquerik commented on wiki/public/js/editor.js
> +  placeholder: "Wiki Content",
```suggestion
  placeholder: "Write your content here...",
```

2024-09-10 14:08 UTC, AyshaHakeem commented
Thank you Shariq for reviewing! @shariquerik 
I have made the suggested changes.

https://github.com/user-attachments/assets/87390a28-2176-4595-b71d-e5220a1fbebc

2024-09-19 18:06 UTC, merged

2024-09-20 06:32 UTC, kittiu commented
Hello, this is quite urgent. My team is working on documentation and more comforatble with rich text.
Is it configurable to use Rich Text?

2024-09-21 09:38 UTC, kittiu commented
> > Note: Just wondering why are we changing the editor?
> 
> Markdown is a standard way of writing docs hence the switch. It take less than an hour to learn Markdown.

OK 👌 just want to get confirmed. Thanks!

2024-09-22 08:16 UTC, kittiu commented
@shariquerik we do have problem with wiki writing pane for our local language.

![image](https://github.com/user-attachments/assets/178f8539-04c2-4260-8eea-5e49f0e7df8e)

This is actually happen in any coding syle pane (i.e., system console) but not rich text. In the pic you will see the cursor position not get along with the real display.

Any hint to solve this?

2024-09-22 11:35 UTC, kittiu commented
May be the problem with ace editor.